### PR TITLE
Bump port_compiler

### PR DESCRIPTION
**Pull request by nifoc**
Fixes an issue with `erl_interface` not being available since OTP23.

### CODE REVIEW

**Comment by tuncer** [comment]
Thanks for the patch! Can you add a commit that changes `macOS-10.13` to `macOS-latest` in `azure-pipelines.yml`? That should fix the macOS build, since 10.13 isn't provided any longer.

**Comment by tuncer** [comment]
And since port_compiler 1.11 is on hex.pm, we can switch it back from git to hex. Let's include that change, too. That means, comment the git spec and enable the line which only says `PCDep = pc`.

**Comment by tuncer** [comment]
@nifoc, I also think it makes sense to migrate from Azure Pipelines to GitHub Actions, since it's out of beta and supports the same features, including Windows and macOS images. Would you be interested in writing a patch for that?

**Comment by nifoc** [comment]
Addressed the first two comments. But it seems like the macOS Pipeline still has issues?

> I also think it makes sense to migrate from Azure Pipelines to GitHub Actions […]

Sure - I will try to take a look at that over the weekend and send a new PR.

**Comment by tuncer** [comment]
I don't know what's wrong with Azure Pipelines, but it's another reason to migrate away. Looking forward to the gh-actions patch! Since the diff is otherwise correct, I'll merge it.

**Pull request merged**
