### PR TITLE
Fix macOS build

### LINKED ISSUE #53: Compilation fails on macos
This line is failing https://github.com/dukesoferl/re2/blob/master/c_src/build_deps.sh#L6

with

```
uname: illegal option -- o
usage: uname [-amnprsv]
```

on mac os

Replicate:

- add `{:re2, git: "git://github.com/dukesoferl/re2.git", tag: "v1.9.4"},` to mix.exs
- `mix deps.get`
- `mix deps.compile`

### PR DESCRIPTION
**Pull request by matehat**
Close #53

### CODE REVIEW

**Comment by matehat** [comment]
@tuncer makes sense, but I don't have a way to check what the output of `uname -s` will be on Windows. Thoughts?

**Comment by matehat** [comment]
@tuncer you're sure about busybox? I just tried

```shell
$ docker run -it --entrypoint sh busybox
$ / uname -o
GNU/Linux
```

**Comment by tuncer** [comment]
Could it be undocumented? https://busybox.net/downloads/BusyBox.html says `uname [-amnrspv]`. Either way, it's a good idea.

**Comment by tuncer** [comment]
I have developed Windows support by testing on Azure Pipelines, since I don't have a Windows machine. Thus, I'd suggest to try it in CI and also echo the value during testing/development. Admittedly, it's inconvenient. Does that work for you?

**Comment by tuncer** [comment]
I have developed Windows support by testing on Azure Pipelines, since I don't have a Windows machine. Thus, I'd suggest to try it in CI and also echo the value during testing/development. But, yeah, it's inconvenient. Does that work for you?

**Comment by nifoc** [comment]
> @tuncer makes sense, but I don't have a way to check what the output of `uname -s` will be on Windows. Thoughts?

A couple of weeks ago I tried adding support for Windows Server 2019 (using GitHub Actions, because I don't have access to a Windows machine either). To debug, I added the following line to `build_deps.sh`:

```bash
echo "$(uname -o) / $(uname -r) / $(uname -v) / $(uname -s)"
```

Output:

```
Msys / 3.0.7-338.x86_64 / 2019-11-21 23:07 UTC / MINGW64_NT-10.0-17763
```

**Comment by matehat** [comment]
Thanks @nifoc! I also tested with Cygwin on a windows vm, and I think I got all cases covered. 

@tuncer, it should be good to go!

**Comment by tuncer** [comment]
Thanks, looks good. If you want to save a few lines, we could initialize both variables before the case statement and remove the catchall. What do you think?

**Comment by tuncer** [comment]
Thanks, looks good. If you want to save a few lines, we could initialize both variables before the case statement and remove the catchall. That way, we'd only modify a single variable in each case, making it harder to introduce mistakes. What do you think?

**Comment by dylan-chong** [comment]
Thanks for fixing this promptly . Really appreciate it :)

**Pull request merged**
